Pillow                        9.3.0
pip                           21.1.2
pluggy                        0.13.1
py                            1.11.0
pycodestyle                   2.11.1
pycparser                     2.22
pyflakes                      3.2.0
PyJWT                         2.8.0
pytest                        6.2.4
pytest-django                 4.4.0
pytest-pythonpath             0.7.3
python3-openid                3.2.0
pytz                          2024.1
requests                      2.26.0
requests-oauthlib             2.0.0
setuptools                    57.0.0
six                           1.16.0
social-auth-app-django        4.0.0
social-auth-core              4.5.4
sqlparse                      0.5.0
toml                          0.10.2
typing-extensions             4.11.0
uritemplate                   4.1.1
urllib3                       1.26.18
wheel                         0.36.2