# Generated by Django 3.2.16 on 2024-05-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20240517_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.SlugField(max_length=256),
        ),
    ]
