# Generated by Django 3.2.16 on 2024-05-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20240517_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.SlugField(max_length=255),
        ),
    ]
